### Introdunction to pandas

In [1]:
print("Introduction to Pandas")

Introduction to Pandas

### Key Data Structures in Pandas
* series
* Dataframes

In [2]:
import pandas as pd

In [5]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [6]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [7]:
df=pd.DataFrame({"names":["Ravi","Harry","Shubham"],"marks":[100,65,76]})

In [8]:
df

     names  marks
0     Ravi    100
1    Harry     65
2  Shubham     76

In [10]:
df=pd.read_csv("D:\\Celebal Technology learning\\Day-06\\tshirts.csv")
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,NaN,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999.0,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":6,""2_stars"":6,""3_stars"":9,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099.0,45.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598.0,55.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
5,8901821,UNDER ARMOUR,Men Charcoal Grey Big Logo SS Printed T-shirt,4.3,64,1999.0,NaN,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/890...,...,"{""1_star"":6,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-8901821""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
6,919032,Roadster,Off-White Black Striped Speckled Pure Cotton ...,3.8,641,899.0,NaN,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/919...,...,"{""1_star"":73,""2_stars"":46,""3_stars"":86,""4_star...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""33.5in"",""value_name"":""B...","[""rw-919032_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
7,18817326,Tommy Hilfiger,Men Beige & Navy Blue Striped Pure Cotton T-shirt,4.4,58,2799.0,40.0,"""₹2,799.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":5,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.03in"",""value_name"":""C...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
8,8426447,WROGN,Men Navy Blue Striped Henley Neck T-shirt,4.2,514,1599.0,50.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/842...,...,"{""1_star"":36,""2_stars"":16,""3_stars"":46,""4_star...",NaN,NaN,"[{""size"":""S"",""value"":""37.25in"",""value_name"":""C...","[""rw-8426447_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
9,20355284,Roadster,The Life Co. Round Neck Raglan Sleeves Typogr...,4.2,74,999.0,53.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/203...,...,"{""1_star"":6,""2_stars"":1,""3_stars"":6,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""28.0in"",""value_name"":""B...",NaN,NaN,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
10,18818696,Tommy Hilfiger,Men White & Black Brand Logo Printed Organic C...,4.4,58,1999.0,40.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":6,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""37.4in"",""value_name"":""C...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
11,9213113,Roadster,The Lifestyle Co Men White Printed Round Neck...,4.1,994,799.0,50.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/921...,...,"{""1_star"":74,""2_stars"":41,""3_stars"":108,""4_sta...","[{""percentage"":""68"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-9213113_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
12,13511732,Puma,Men Black Solid Run Fav 1/4 Zip T-Shirt,4.4,167,3999.0,NaN,"""₹3,999.00""",INR,http://assets.myntassets.com/assets/images/135...,...,"{""1_star"":11,""2_stars"":6,""3_stars"":7,""4_stars""...","[{""percentage"":""57"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""34.65in"",""value_name"":""...","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
13,13591994,Camey,Men Maroon Solid Round Neck T-shirt,3.5,2,999.0,60.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""L"",""value"":""40.0in"",""value_name"":""Ch...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
14,21439050,Kappa,Men Typography Printed Cotton T-shirt,3.2,9,599.0,30.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XS"",""value"":""35.0in"",""value_name"":""C...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
15,13615634,U.S. Polo Assn.,Men Red Solid Mandarin Collar T-shirt,4.5,69,1699.0,40.0,"""₹1,699.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":2,""2_stars"":3,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
16,13620624,Roadster,The Lifestyle Co Men White Brand Logo Appliqu...,4.0,154,1399.0,73.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":12,""2_stars"":10,""3_stars"":18,""4_star...","[{""percentage"":""68"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
17,13502414,Puma,Men Navy Blue & White Performance Cat Printed ...,4.3,327,1499.0,NaN,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/135...,...,"{""1_star"":22,""2_stars"":11,""3_stars"":22,""4_star...","[{""percentage"":""78"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""36.61in"",""value_name"":""...","[""rw-13502414_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
18,13621134,Roadster,The Lifestyle Co Men Rust Brown Solid Appliqu...,4.1,312,1399.0,50.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":27,""2_stars"":18,""3_stars"":31,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
19,17686030,Allen Solly Tribe,Men Navy Blue Solid T-shirt,4.3,23,1499.0,30.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
20,13616400,Arrow New York,Men Beige Printed Round Neck Pure Cotton T-shirt,4.8,13,899.0,25.0,"""₹674.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
21,13480864,Aeropostale,Men White Printed Round Neck Pure Cotton T-shirt,4.2,13,1199.0,NaN,"""₹1,199.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
22,13622338,Roadster,The Lifestyle Co Men Olive Green Solid Round ...,4.4,54,899.0,55.0,"""₹404.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":1,""2_stars"":3,""3_stars"":2,""4_stars"":...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",MAI███ KN███EAR███,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,BEH███ HP███S A█████████LL ███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
23,16295686,Miss & Chief,Boys Pack of 3 Printed T-shirt,3.9,7,1995.0,71.0,"""₹578.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Home,"[{""size"":""2-3Y"",""value"":""24.4in"",""value_name"":...",NaN,Hom███and███B/1█████████ Am███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
24,16298856,Friskers,Men Pack of 2 Printed Pure Cotton T-shirts,0.0,0,2998.0,59.0,"""₹1,229.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Fly███,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,"Fla███o 6███jay█████████s, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
25,16277914,Parx,Men Black Printed Polo Collar T-shirt,4.9,7,1399.0,53.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Ray███d L███ted███,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C...",NaN,"RAY███D L███TED█████████, P███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
26,16292318,Bewakoof,Men White Printed Pockets T-shirt,4.2,17,1399.0,60.0,"""₹549.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Tight""...",Bew███of ███nds█████████Lim██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,"Plo███8, ███ Fl█████████lr,███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
27,19201678,Tokyo Talkies,Women Yellow Printed Extended Sleeves Slim Fit...,4.1,103,699.0,58.0,"""₹293.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":4,""2_stars"":8,""3_stars"":10,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,3rd███oor███o. █████████Mai███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
28,16923916,Monte Carlo,Women Pack Of 2 Blue & Peach Solid V-Neck Pure...,4.8,13,835.0,25.0,"""₹835.00""",INR,http://assets.myntassets.com/assets/images/169...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""32.0in"",""value_name"":""To...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
29,10143909,CHKOKKO,Chkokko Men Teal Green Solid Round Neck Traini...,3.7,53,1665.0,70.0,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":10,""2_stars"":1,""3_stars"":11,""4_stars...","[{""percentage"":""72"",""value_name"":""Fit, Just Ri...",DLA███OSS███IVA█████████D,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,FLO███FIR███ B █████████8/1███████████████████...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
30,20085320,BULLMER,Men Pack of 2 Navy Blue & Turquoise Blue Long ...,4.8,12,3998.0,80.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bod███ove███par█████████,"[{""size"":""M"",""value"":""39.0in"",""value_name"":""Ch...",NaN,Bod███ove███par█████████ No███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
31,10555034,Braveo,Men Navy Blue and Red Checked Round Neck Pure ...,0.0,0,1099.0,65.0,"""₹384.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bra███For███es,"[{""size"":""S"",""value"":""37.5in"",""value_name"":""Ch...",NaN,"SF.███. 8███Vad█████████am,███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
32,12987894,AMERICAN EAGLE OUTFITTERS,Women White & Yellow Printed Round Neck T-shirt,4.4,5,1799.0,80.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Wes███ry ███din█████████d_M██████,"[{""size"":""XS"",""value"":""29.0in"",""value_name"":""T...",NaN,"Gro███ Fl███, N█████████old███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
33,12953958,Allen Solly,Men Maroon Solid Polo Collar Pure Cotton T-shirt,4.4,409,999.0,40.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/129...,...,"{""1_star"":17,""2_stars"":6,""3_stars"":26,""4_stars...","[{""percentage"":""96"",""value_name"":""Fit, Just Ri...",Wes███ry ███din█████████d_M██████,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...","[""rw-12953958_cae700"",""https://videos.myntasse...","Gro███ Fl███, N█████████old███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
34,22629260,max,Striped Polo Collar Short Sleeves T-shirt,4.4,7,799.0,40.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Lan███rk ███ine█████████t L███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,#41███42/███bla█████████ pa███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
35,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599.0,58.0,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MAD███R P███T P█████████MIT███,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",NaN,621███ 6n███ kh█████████zia███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
36,19206288,FERANOID,Men Purple Henley Neck Bio Finish T-shirt,4.2,21,1199.0,50.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":5,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Fer███id,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,B15███ SH███MAR█████████RK ███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
37,19264534,Flying Machine,Men Black & White Printed Pure Cotton Slim Fit...,4.0,102,999.0,61.0,"""₹389.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":15,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
38,19264536,Flying Machine,Men Rust Orange Melange Pure Cotton Slim Fit T...,3.8,60,1299.0,61.0,"""₹506.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":5,""2_stars"":7,""3_stars"":7,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [11]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,NaN,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999.0,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":6,""2_stars"":6,""3_stars"":9,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099.0,45.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598.0,55.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [12]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
34,22629260,max,Striped Polo Collar Short Sleeves T-shirt,4.4,7,799.0,40.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Lan███rk ███ine█████████t L███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,#41███42/███bla█████████ pa███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
35,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599.0,58.0,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MAD███R P███T P█████████MIT███,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",NaN,621███ 6n███ kh█████████zia███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
36,19206288,FERANOID,Men Purple Henley Neck Bio Finish T-shirt,4.2,21,1199.0,50.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":5,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Fer███id,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,B15███ SH███MAR█████████RK ███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
37,19264534,Flying Machine,Men Black & White Printed Pure Cotton Slim Fit...,4.0,102,999.0,61.0,"""₹389.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":15,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
38,19264536,Flying Machine,Men Rust Orange Melange Pure Cotton Slim Fit T...,3.8,60,1299.0,61.0,"""₹506.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":5,""2_stars"":7,""3_stars"":7,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [13]:
df.describe()

         product_id     rating  ratings_count  initial_price   discount
count  3.900000e+01  39.000000      39.000000      39.000000  32.000000
mean   1.547068e+07   3.876923     120.897436    1478.358974  52.312500
std    4.391180e+06   1.198346     206.471075     788.897548  14.510147
min    9.190320e+05   0.000000       0.000000     599.000000  25.000000
25%    1.350707e+07   3.900000       8.000000     999.000000  40.000000
50%    1.629232e+07   4.200000      54.000000    1299.000000  53.000000
75%    1.901019e+07   4.400000     102.500000    1632.000000  60.250000
max    2.262926e+07   4.900000     994.000000    3999.000000  80.000000

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              39 non-null     int64
 1   title                   39 non-null     str
 2   product_description     39 non-null     str
 3   rating                  39 non-null     float64
 4   ratings_count           39 non-null     int64
 5   initial_price           39 non-null     float64
 6   discount                32 non-null     float64
 7   final_price             39 non-null     str
 8   currency                39 non-null     str
 9   images                  39 non-null     str
 10  delivery_options        39 non-null     str
 11  product_details         39 non-null     str
 12  breadcrumbs             39 non-null     str
 13  product_specifications  39 non-null     str
 14  amount_of_stars         39 non-null     str
 15  what_customers_said     30 non-null     str
 16  seller_name             18 non-null     str
 17  sizes                   39 non-null     str
 18  videos                  10 non-null     str
 19  seller_information      18 non-null     str
 20  variations              14 non-null     str
 21  best_offer              39 non-null     str
 22  more_offers             39 non-null     str
 23  category                39 non-null     str
dtypes: float64(3), int64(2), str(19)
memory usage: 7.4 KB

### Data Selection

In [16]:
type(df["title"])

pandas.Series

In [17]:
df["title"]

0                         ether
1                Mast & Harbour
2                Mast & Harbour
3                   Urbano Plus
4                       ScoldMe
5                  UNDER ARMOUR
6                      Roadster
7                Tommy Hilfiger
8                         WROGN
9                      Roadster
10               Tommy Hilfiger
11                     Roadster
12                         Puma
13                        Camey
14                        Kappa
15              U.S. Polo Assn.
16                     Roadster
17                         Puma
18                     Roadster
19            Allen Solly Tribe
20               Arrow New York
21                  Aeropostale
22                     Roadster
23                 Miss & Chief
24                     Friskers
25                         Parx
26                     Bewakoof
27                Tokyo Talkies
28                  Monte Carlo
29                      CHKOKKO
30                      BULLMER
31                       Braveo
32    AMERICAN EAGLE OUTFITTERS
33                  Allen Solly
34                          max
35               Mad Over Print
36                     FERANOID
37               Flying Machine
38               Flying Machine
Name: title, dtype: str

In [22]:
df[["title", "ratings_count"]]

                        title  ratings_count
0                       ether             70
1              Mast & Harbour            200
2              Mast & Harbour             72
3                 Urbano Plus              6
4                     ScoldMe              0
5                UNDER ARMOUR             64
6                    Roadster            641
7              Tommy Hilfiger             58
8                       WROGN            514
9                    Roadster             74
10             Tommy Hilfiger             58
11                   Roadster            994
12                       Puma            167
13                      Camey              2
14                      Kappa              9
15            U.S. Polo Assn.             69
16                   Roadster            154
17                       Puma            327
18                   Roadster            312
19          Allen Solly Tribe             23
20             Arrow New York             13
21                Aeropostale             13
22                   Roadster             54
23               Miss & Chief              7
24                   Friskers              0
25                       Parx              7
26                   Bewakoof             17
27              Tokyo Talkies            103
28                Monte Carlo             13
29                    CHKOKKO             53
30                    BULLMER             12
31                     Braveo              0
32  AMERICAN EAGLE OUTFITTERS              5
33                Allen Solly            409
34                        max              7
35             Mad Over Print              5
36                   FERANOID             21
37             Flying Machine            102
38             Flying Machine             60

In [23]:
type(df.iloc[0])

pandas.Series